# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'Call and Messages' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'MessageBox'
	pod 'MessageKit'

  # Pods for Call and Messages

end
